language: node_js
node_js:
- '8.10'
before_script:
- node make.js build
before_deploy:
- node make.js after_build
deploy:
  provider: npm
  email: wparad@gmail.com
  api_key:
    secure: DPgK8RUtZ1TLXMb+iJVdbCGgxzJvqdzE+rSvLyFpIy1rsPdNEvok5pJLocJeJJ5gSBwzVduYgl7qVJHvwYi8eJxqPna4MoZ9HpEuTAzf2POLFSbsza7Szv7md3rkaE3lB9wN0R43iE+UarMAYzFjQoLUok97TDQzC+be1wSLPRhtlJwucWzwNI6ADLKhPWY85bUtwpdZRJD+rwvorz31i+yhKDi3x0puMOHpmjrm9NalSxJR1NKU5BW0MppaCoVqdr3ZIEWIKLnUH1ufRTs2xRHoJ+6u9jKI0i2DKttv+QwX9Btgtw3ytcVf4TOA3Pd8X4ZTEN5E+ZowUFI2GfVeP1jaPVy0Dy4wNKt4sLymJ4kvaUPlPpTI12wGL9NZdwbCJR8uCxaVv8BHVXesKp9BZ76rUb9+FKpTXH3zzW94k/izBVKOuDs98D56i68s9S9qEJYQ584gOGX3FvYLYFdiU2R8QvN0nm0JstnRaI9nt05OR4iQlgTvBM0qHPf8Es1u0hQhrIVmTdir0ln7e194y/aQhkVeiQKdA9ogEWVyjJxYdAhscX62IRJKBoLtwHsYJKfAUJo+f68DZ8ScfgrqInXbTglxbjUQ/CHq+G4YvumhjGCHgD+odWBkhoZArvL/DbesX8bACrftnCplFTSVL5+go4k1+aLFMdF1TR54rlk=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
  - secure: FtaGozL5ryINiYnypAa+oabqEXEVg0fBDwK+sRfeSsYzIluh+qaXdu0bnlbxrtj4Brr8Hvo0LAz0faJrBd3CzpLDPPP3DtJ4ORfoPCUyZmNmhvnW7ixSIUxE0jI7h/XZP8xv+qtzJB62gigs7MkCetfhl5NfGIr2BwS+LhGzpfbvh670K5CqR8NA0y7Qj6v2Xzc0gufw1WnETrM4eif/neOJwvaUQoNXdjT6pdXGVVTu5D/7ZGzbp91ov5n2VNJ5GMVPOkk+QnHhJGdImTGThJV94CLz12rQI446DnAZYBUKm25zYAa5UKNSkA6ZmWEFuIvLqU0G4+n8AZ//HmlnkabYwJVRwhPf8/a87Aw4/eNWNgMAqaLJ4dwue8tYv53gf090RmSBIrOhJqbBbjz5VX7inrhnKJO75FqGKLqVeJU2Elr2qCOUU6yV95L6zf9QFL9J+F1EHVVHp+z9OkFrqpbCRXtt96JGR5uPmPh4SpOsb9LalduTgP0a+f3Jnks0uI0RDG+bdE+zrG4QaA3hUoZj4yW9GjZ4akmAfs9vMD29S5DMbrhDrWhq6AYOmOJKntaHq3navL9lp//P/c+eE1WLHCGpPPnWGbgMojoQrdhHIrmliDnnvms18bONj91ZjOUiY0lounO0QsqOT9UzkuCrlKOtjLZLScbvewwsYUQ=
